[application]

[web.app]

# HTML title tag content
title = "vault"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = [
    "https://cdn.jsdelivr.net/npm/jdenticon@3.3.0/dist/jdenticon.min.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
